### ISSUE TITLE
Flickity doesn't swipe on mobile chrome when using via npm package

### ISSUE THREAD

**Issue by exophunk** [drewjbartlett/vue-flickity#10]
I have troubles make flickity work when using as a npm package . It is likely related to the build process with laravel-mix, webpack and bubel transpiler.

Touch Swiping stops working on mobile chrome (and chrome dev simulator), but only with the mentioned build process.

I asked about it here: https://github.com/metafizzy/flickity/issues/540

Does anyone experience similar issues with a similiar build process?

**Comment by DerekBess** [comment]
@exophunk 

I too just noticed the same issue on a site I have in development.

Adding this to my CSS has helped combat the issue for me.

`touch-action: manipulation;`

**Comment by exophunk** [comment]
@DerekBess where did you add this css property to? The flickity container? the inner carousel elements?

**Comment by itsduc** [comment]
Any news on this?

**Comment by drewjbartlett** [comment]
Is this a flickity issue or an issue with the vue component? This component is only a wrapper on top of flickity.

**Comment by jmharveys** [comment]
it's a Flickity issue.

**Comment by drewjbartlett** [comment]
Closing this since it's the wrong place for this
