### ISSUE TITLE
Re-init multiple carousels

### ISSUE THREAD

**Issue by mbarwick83** [drewjbartlett/vue-flickity#16]
Is there a way to, or suggestion, on how I'd go about re-initing several (dynamic) flickity carousels used in a SPC? 

I'm having no luck with `this.$refs.flickity.rerender()`, probably because there are multiple carousels using this `ref`.

Any ideas?

**Comment by drewjbartlett** [comment]
Couldn't you loop them like so:

```js
this.$refs.flickity.forEach(flickityComponent => {
   flickityComponent.rerender();
});
```

**Comment by mbarwick83** [comment]
You're the man. I tried this and was calling the `flickityComponent` wrong, didn't have `Component`.
Appears to be working now, thanks dude. Ps: thanks for the component!

**Comment by drewjbartlett** [comment]
Glad to hear it! And no problem @mbarwick83 👍
