### ISSUE TITLE
selectedIndex() doesn't update

### ISSUE THREAD

**Issue by homerjam** [drewjbartlett/vue-flickity#18]
I'm trying to display an image counter which gets the `selectedIndex()` via computed properties however the `selectedIndex()` is never updated. Should this plugin react to flickity events so Vue knows when to update the computed properties?

**Comment by drewjbartlett** [comment]
That might be worth implementing. If you wanna submit a PR for it, feel free!

**Comment by MackieLee** [comment]
maybe you used ES6 arrow function, if you did this,  data will not update.

**Comment by drewjbartlett** [comment]
I think I see the issue here. It's under methods when it really should be under computed.

**Comment by apansky** [comment]
Hey, i have similiar question. Is there any way to know which slide is currently active? or are there any events when calling prev/next slide which i can listen to? thanx !

**Comment by drewjbartlett** [comment]
@apansky Flickity docs would be a better place for that probs.
