### ISSUE TITLE
Error with v-for

### ISSUE THREAD

**Issue by angelorc** [drewjbartlett/vue-flickity#2]
Hello,
I tried the component, but if I try to add v-for the elments gona be outside the view port

```
<div class="carousel-cell col-xs-6 col-md-3" v-for="package in packages">
           <button class="block-size unbuttonized" :class="{ 'active': package.active }">
                <div class="pricing">
                    <div class="price">
                        <span class="symbol">{{ package.currency }} </span>
                        <span class="cost">{{ package.price }}</span>
                        <span class="period">{{ package.periodText }}</span>
                    </div>
                    <div class="price old">
                        <span class="cost">{{ package.currency }} {{ package.price_old }}</span>
                        <span class="period">{{ package.price.periodText }}</span>
                    </div>
                </div>
                <div class="details">
                    <span v-for="feature in package.features" v-html="feature.name"></span>
                </div>
            </button>
        </div>
```
Rendering:
```html
<div class="main-carousel flickity-enabled is-draggable" tabindex="0">
  <div class="flickity-viewport" style="height: 0px;">
    <div class="flickity-slider" style="left: 0px;"></div>
  </div>
  <button class="flickity-prev-next-button previous" type="button" disabled="" aria-label="previous"><svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" class="arrow"></path></svg></button><button class="flickity-prev-next-button next" type="button" disabled="" aria-label="next"><svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" class="arrow" transform="translate(100, 100) rotate(180) "></path></svg></button><ol class="flickity-page-dots"></ol><div class="carousel-cell col-xs-6 col-md-3"><button class="block-size unbuttonized"><div class="pricing"><div class="price"><span class="symbol">€ </span> <span class="cost">3.90</span> <span class="period">/mo</span></div> <div class="price old"><span class="cost">€ 7.90</span> <span class="period"></span></div></div> <div class="details"><span>Dominio <strong>Incluso</strong></span><span>Spazio Web da <strong>10GB</strong></span><span>Traffico mensile <strong>Illimitato</strong></span><span>Database MySQL <strong>Illimitati</strong></span></div></button></div><div class="carousel-cell col-xs-6 col-md-3"><button class="block-size unbuttonized"><div class="pricing"><div class="price"><span class="symbol">€ </span> <span class="cost">7.90</span> <span class="period">/mo</span></div> <div class="price old"><span class="cost">€ 12.90</span> <span class="period"></span></div></div> <div class="details"><span>Dominio <strong>Incluso</strong></span><span>Spazio Web da <strong>20GB</strong></span><span>Domini aggiuntivi <strong>Illimitati</strong></span><span>Traffico mensile <strong>Illimitato</strong></span><span>Database MySQL <strong>Illimitati</strong></span></div></button></div><div class="carousel-cell col-xs-6 col-md-3"><button class="block-size unbuttonized"><div class="pricing"><div class="price"><span class="symbol">€ </span> <span class="cost">11.90</span> <span class="period">/mo</span></div> <div class="price old"><span class="cost">€ 23.90</span> <span class="period"></span></div></div> <div class="details"><span>Dominio <strong>Incluso</strong></span><span>Spazio Web da <strong>30GB</strong></span><span>Domini aggiuntivi <strong>Illimitati</strong></span><span>Traffico mensile <strong>Illimitato</strong></span><span>Database MySQL <strong>Illimitati</strong></span></div></button></div>
</div>
```

**Comment by drewjbartlett** [comment]
Could you provide some more details on this? I'm not totally sure what you mean.

**Comment by brettgullan** [comment]
I'm having the same issue. If I try to generate the `carousel-cell` elements using a `v-for` binding, there are rendered outside the Flickity wrapper.

**Comment by angelorc** [comment]
same here... it re-render outside

**Comment by drewjbartlett** [comment]
Hmmm, I'll look into this. @brettgullan could you give me a code sample as well?

**Comment by brettgullan** [comment]
Hey @drewjbartlett Sorry, false alarm! Found the issue with my code. All good.

**Comment by drewjbartlett** [comment]
Oh good! Closing this for now then!

**Comment by lukaszflorczak** [comment]
Hi. I have the same issue. I use v-for and my slides are outside of the flickity wrapper.

**Comment by liquidvisual** [comment]
@lukaszflorczak Yep, I'm having the exact same issue. 

@drewjbartlett Can you please tell us how you solved this?

**Comment by liquidvisual** [comment]
@drewjbartlett Could you please re-open this issue? It's such show-stopping bug I'm uncertain how anyone is actually using this component with any sort of data driven loop. Noone has discussed an answer yet :/

**Comment by alexbudure** [comment]
+1 Flickity initializes before the loop ends

**Comment by exxy** [comment]
@alexbudure is correct

You can remedy this issue by using a `v-if` to delay the rendering of the Flickity component until your data is available.

Example:
`<flickity v-if="Object.keys(slides).length > 0" ref="flickity" class="carousel" :options="flickityOptions">
    <div class="carousel-cell" v-for="(item, index) in slides" :key="index">
        {{ item.title }}
    </div>
</flickity>`

**Comment by SherAtrium** [comment]
> @alexbudure is correct
> 
> You can remedy this issue by using a `v-if` to delay the rendering of the Flickity component until your data is available.
> 
> Example:
> 
> ```
> <flickity v-if="Object.keys(slides).length > 0" ref="flickity" class="carousel" :options="flickityOptions">
>     <div class="carousel-cell" v-for="(item, index) in slides" :key="index">
>         {{ item.title }}
>     </div>
> </flickity>
> ```

Wow thanks dude. You saved me. )))

**Comment by SherAtrium** [comment]
> @alexbudure is correct
> 
> You can remedy this issue by using a `v-if` to delay the rendering of the Flickity component until your data is available.
> 
> Example:
> 
> ```
> <flickity v-if="Object.keys(slides).length > 0" ref="flickity" class="carousel" :options="flickityOptions">
>     <div class="carousel-cell" v-for="(item, index) in slides" :key="index">
>         {{ item.title }}
>     </div>
> </flickity>
> ```

Wow thanks dude. You saved me. )))

**Comment by jakedowns** [comment]
downside of using v-if to solve this, is that it breaks the `this.$refs.flickity` :<

**Comment by semihkeskindev** [comment]
> @alexbudure is correct
> 
> You can remedy this issue by using a `v-if` to delay the rendering of the Flickity component until your data is available.
> 
> Example:
> 
> ```
> <flickity v-if="Object.keys(slides).length > 0" ref="flickity" class="carousel" :options="flickityOptions">
>     <div class="carousel-cell" v-for="(item, index) in slides" :key="index">
>         {{ item.title }}
>     </div>
> </flickity>
> ```

I was working on it for 3 hours to figure it out why act like this... Thank you so much :pray: It worked for me.
