### ISSUE TITLE
How to use append

### ISSUE THREAD

**Issue by jmharveys** [drewjbartlett/vue-flickity#22]
Hi, 

sorry to write over here, but I don't get it how to use the 

> append

 function with vue-flickity.

`this.$refs['flickityCarousel_' + this.uid].append('<div>Append this thing into my carousel</div>')`
 is not working. I would like to append a new slice, once my slider is mounted.

If I put a console.log into the vue-flickity.vue file for testing, I've got my element in the console, but it's not append to the carousel.

Any clue?

Thanks

**Comment by groman00** [comment]
@jmharveys Try using a class name for your flickity cells and then adding that class name as the cellSelector option.

`this.$refs['flickityCarousel_' + this.uid].append('<div class="my-flickity-cell">Append this thing into my carousel</div>')`

```
data() {
    return {
        flickityOptions: {
            cellSelector: '.my-flickity-cell'
        }
    };
}
```

**Comment by jmharveys** [comment]
Thank you!
