### ISSUE TITLE
Occur TypeError: _vueFlickity2.default is not a constructor

### ISSUE THREAD

**Issue by aloha1003** [drewjbartlett/vue-flickity#24]
my vue code :
` import Flickity from 'vue-flickity';
export default {
    data () {
      return {
        flkty:{},
        flickityOptions: {
                initialIndex: 2,
                prevNextButtons: false,
                pageDots: false,
                adaptiveHeight:true,
                autoPlay: true,
                setGallerySize:true,
                cellAlign: 'left',
                contain: true,
                freeScroll: true,
                wrapAround: false
            },
       mounted: function() {
                         var elem = document.querySelector('.flickity-enabled');
                         self.flkty = new Flickity(self.$el, self.flickityOptions);
        }
}
`  
But I Got TypeError: _vueFlickity2.default is not a constructor

**Comment by drewjbartlett** [comment]
Closing this unless you are still getting this error
