### ISSUE TITLE
staticClick

### ISSUE THREAD

**Issue by antoinejaunard** [drewjbartlett/vue-flickity#26]
Hey,
Is it possible to use [staticClick](https://flickity.metafizzy.co/events.html#staticclick) with this Vue version of Flickity?
If not, would it be possible to add it?
Thanks for your work,
Antoine

**Comment by camilodelvasto** [comment]
This seems to be already implemented... I was able to listen to the event by doing this:
```html
<!-- template -->
<div class="carousell-cell" @click="goToFlickity('thisRef', '/new-route')>
```
```javascript
// methods
goToFlickity(id, route) {
  var vm = this
  this.$refs[id].on('staticClick', function(event, pointer, cellElement, cellIndex) {
    vm.$router.push(route)
  })
}
```
I guess this can be closed :)

**Comment by camilodelvasto** [comment]
I used it like this, on the mounted hook:
```Javascript
this.$refs['myref'][0].flickity.on('staticClick', function(event, pointer, cellElement, cellIndex) {
  if (!cellElement) {
    return;
  }
  // some action here
})
```
so I guess it pretty much works and this should be closed :)

**Comment by antoinejaunard** [comment]
Thanks for your reply @camilodelvasto.
