### ISSUE TITLE
Does not work with TypeScript

### ISSUE THREAD

**Issue by PhouvanhKCSV** [drewjbartlett/vue-flickity#28]
Hi, it is look like vue-flickity does not work when using Vue with TypeScript.

My code is:
`import Flickity from 'vue-flickity'`

Then i get the following error.
`TS2307: Cannot find module 'vue-flickity'.`

Does anyone have the error like this, Thank you.

**Comment by drewjbartlett** [comment]
@PhouvanhKCSV I'm not a TS person. Feel free to submit a PR to support this.

**Comment by behnamt** [comment]
For anyone that is still looking for answers:

* add below to you your @types
```
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
}
```

* add vue-loader to your webpack.confg
* import like this
```
import Flickity from 'vue-flickity/src/flickity.vue';
```

**Comment by drewjbartlett** [comment]
@behnamt would you be willing to make a PR to support this with typescript?
