### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [drewjbartlett/vue-flickity#3]
I get this error

```
Uncaught Error: Cannot find module "flickity"
```

**Comment by drewjbartlett** [comment]
Did you run `npm install vue-flickity --save`? You can also try `npm install flickity --save` if need be.

**Comment by FrancescoSaverioZuppichini** [comment]
Now it works, but is all bugged

**Comment by drewjbartlett** [comment]
Can you explain all bugged? I installed this twice yesterday and used it on two different sites with no errors so I'm curious to know what's going on with yours.

**Comment by ntnelson1s** [comment]
AHHH! Wanted to chime in here. Was stuck on an error forever where I could not resolve module when simply using "import Flickity from 'vue-flickity';". What fixed it was also installing the regular flickity dependency as you stated about.

**Comment by drewjbartlett** [comment]
That's so strange. It works fine on new projects for me without previously having flickity as a dependency. I just checked the package.json file and saw that vue and flickity are both in a as devDependencies. I wonder if switching them to dependencies will fix it. I'll give it a go as soon as I have a moment

**Comment by fvmedia** [comment]
+1 I pulled the package, and just as a test, moving the dependancy up to a main dependancy and not dev will fix the issue
