### ISSUE TITLE
pageDots are not shown

### ISSUE THREAD

**Issue by ngtlin** [drewjbartlett/vue-flickity#35]
When using Flickity options, pageDots: true. I do see the underlined flickity instance do created pageDots elements. But nothing is visible on the screen.

**Comment by ngtlin** [comment]
As a work around by adding a dummy Vue component, the pagination dots appear.

**Comment by sheriffderek** [comment]
Did you ever solve your problem? It's hard for me to tell what it is. Try adding some more description or - if you solved it, maybe close this.

**Comment by ngtlin** [comment]
Yes, I have found a solution.
