### ISSUE TITLE
Allow hooking on to flickity events

### ISSUE THREAD

**Issue by exophunk** [drewjbartlett/vue-flickity#6]
Flickity provides events to listen to: http://flickity.metafizzy.co/events.html

It seems this is not possible with vue-flickity, as there is no method for that in the wrapper:

`this.$refs.flickity.on('select', this.doSomething)` does not work, as the "on" method is unknown. Could you simply add this and pass it to flickity as all the other methods?

Or is there another, better way to do this?

**Comment by drewjbartlett** [comment]
Hey thanks for catching this! I added support just now in `v1.0.7`;

Given you have a $ref named `slider`, you can now do this like: 

```javascript

mounted () {
   let vm = this;

   this.$refs.slider.on('select', function () {
      console.log(vm.$refs.slider.flickity.selectedIndex);
   });
}
```

**Comment by CHEWX** [comment]
@siberiadev Late response, but I assume you set the ref to `slider`
