### ISSUE TITLE
Work with bgLazyLoad

### ISSUE THREAD

**Issue by cpury** [drewjbartlett/vue-flickity#7]
Great package!

To get `bgLazyLoad: true` to work, I need to install https://github.com/metafizzy/flickity-bg-lazyload . I tried installing it via `npm install flickity-bg-lazyload --save`, but my `data-flickity-bg-lazyload` attributes just get ignored.

Have you tried using add-on packages like this? Any ideas how to get them to work?

Thanks!

**Comment by cpury** [comment]
Ok I got it to work. Simply imported `flickity-bg-lazyload` in my component after importing `vue-flickity`. It then patches the existing `Flickity` variable.

Of course that's not the cleanest way of doing this, maybe you might consider adding some nicer API 😃

**Comment by pmochine** [comment]
Thanks! Just for future readers:

    import VueFlickity from 'vue-flickity';
    require('flickity-bg-lazyload');
