### ISSUE TITLE
Implementation with images

### ISSUE THREAD

**Issue by rugor** [drewjbartlett/vue-flickity#8]
This is an implementation question.

Works great with coloured background divs like in the example, but images come in late, after the plugin has fired. How does one load images with Flickity in Vue? Use nextTick somehow? 

In typical webpages an imagesLoaded callback does the trick. What is the equivalent strategy in a vue component?

**Comment by drewjbartlett** [comment]
I'm not sure this is the right place to ask this. But would you mind sharing some code and I'll have a look to see if I can be of any help? :)

**Comment by rugor** [comment]
Perhaps, but a common use case for Flickity is with images and I can't find an example of that here -- so it may be appropriate. 

The issue is described in this example http://flickity.metafizzy.co/options.html#imagesloaded and here: http://codepen.io/desandro/pen/MYQWEe

I have an array of images I want to share with the component but it doesn't render correctly sometimes because Flickity fires before the images are loaded. How have you been able render images successfully with this component? Or maybe I need to pull in imagesLoaded too

**Comment by elHornair** [comment]
@rugor I had the same issue, but luckily in my case all the images were the same size, so I gave fixed dimensions to their containers with CSS - That way, Flickity doesn't have to wait for the images to be fully loaded for correctly rendering the items

**Comment by davekiss** [comment]
This library fixed the issue for me: https://github.com/David-Desmaisons/Vue.ImagesLoaded

**Comment by pjhartin** [comment]
@davekiss - When you say it fixed it, how did it fix it, what did you hook into when the image was processed?

**Comment by rugor** [comment]
@pjhartin 

import the package:

`import imagesLoaded from 'vue-images-loaded'`

add the directive:

`directives: {
    imagesLoaded
  }`

then on your flickity component: 

```
<flickity ref="flickity" :options="flickityOptions" v-images-loaded="imgsLoaded">
    <img :src="image.image" alt="" v-for="(image, index) in images" :key="index">
</flickity>
```

`v-images-loaded` triggers the method `imgsLoaded` 

which can turn the opacity from 0 to 1 for each image ... at once or all together depending on how you configure the directive.

**Comment by pjhartin** [comment]
@rugor 

Thanks mate for the clarification. I actually was wondering about the issue where images are dynamically added but it causes a problem where Flickity wouldn't resize properly: https://flickity.metafizzy.co/options.html#imagesloaded

I got it in the end by adding a reference to Flickity and calling the `reloadCells` function.

```
imgsLoaded(instance, image) {
      // Reload flickity cells due to height change post
      let flickityInstance = this.$refs.flickity;
      flickityInstance.reloadCells();
    }
```
