### ISSUE TITLE
can't  npm install vue-flickity

### ISSUE THREAD

**Issue by lokialone** [drewjbartlett/vue-flickity#9]
report error as follow: 

     npm install vue-flickity --save
     npm ERR! registry error parsing json
     npm ERR! Darwin 16.4.0
     npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "vue-flickity" "--save"
     npm ERR! node v6.3.1
     npm ERR! npm  v3.10.9
     npm ERR! Unexpected token < in JSON at position 0
     npm ERR! <html>
     npm ERR! <head><title>403 Forbidden</title></head>
     npm ERR! <body bgcolor="white">
     npm ERR! <center><h1>403 Forbidden</h1></center>
     npm ERR! <hr><center>nginx</center>
     npm ERR! </body>
     npm ERR! </html>

**Comment by drewjbartlett** [comment]
I think this is a problem with your version of npm and not vue-flickity. I may be wrong though.
